# Generated by Django 4.1.3 on 2022-12-12 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('birthday', models.DateField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('contact', models.CharField(max_length=12)),
                ('alternat_no', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=300)),
                ('permanent_address', models.CharField(max_length=500)),
                ('intrested', models.CharField(max_length=150)),
                ('lead_sources', models.CharField(max_length=150)),
                ('remarks', models.TextField(max_length=500)),
                ('assigned', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=150)),
                ('date_create', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('led_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.leadcreate')),
            ],
        ),
        migrations.CreateModel(
            name='Call_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cls', models.CharField(max_length=50)),
                ('rem', models.CharField(max_length=250)),
                ('str_dt', models.CharField(max_length=50)),
                ('end_dt', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('led_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.leadcreate')),
            ],
        ),
    ]
