# Generated by Django 4.1.3 on 2022-12-12 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StaffManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=30)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StaffManager.employee_register')),
            ],
        ),
    ]
